file_format: "1"
id: mk1
name: mk1
type: shield
url: https://github.com/Badjau/zmk-config-mk1
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - mk1_left
  - mk1_right